### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pcworld** [fatalis/witcher3weight#1]
Current LICENSE.txt says:

> who gives a shit

However, I give a shit and would like to reuse some of your code for a Witcher 3 mod. So please consider publishing this under some free license. 
Edit: Preferably a non-viral license so that the code can be used in DLLs for Witcher 3.

**Comment by fatalis** [comment]
aka public domain

**Comment by fatalis** [comment]
fixed

**Comment by pcworld** [comment]
Thank you!
